k8s_cluster_scanner:
  description: >
    Perform a meticulous scan of the Kubernetes cluster to identify all namespaces and deployments explicitly labeled with "starfall.io/enabled=true".
    For each matching deployment, extract and report:
      - Namespace name
      - Deployment name
      - For every container: name, image, image tag, and current version
      - All deployment labels
    Additionally, capture the Kubernetes cluster's current version and the timestamp of the scan.
    The output must be a structured, machine-readable, JSON, report that enables downstream agents 
    and humans to easily assess upgrade eligibility, plan actions, and track changes over time.
    Exclude any deployments or namespaces that do not have the specified label.
    Do not perform any upgrade or modification actions; your sole responsibility is to scan and report.
    
  expected_output: >
    A validated K8sClusterScanResult object with the following structure:
      kubernetes_control_plane:
        current_version: <Current Kubernetes control plane version string>
        latest_version: <Latest available Kubernetes version (to be filled by discovery task)>
        name: "Kubernetes"
        scanned_at: <ISO8601 UTC timestamp of scan>
      apps: List of deployments, each with:
        - name: <Deployment name>
        - namespace: <Namespace name>
        - deployment: <Deployment identifier>
        - containers: List of containers, each with:
            - name: <Container name>
            - image: <Full image path>
            - current_version: <Image tag or version>
        - labels: Dictionary of deployment labels

  agent: platform_engineer


